import java.util.*;

/**
 * Problem statement: Given a word, write a function to generate all of its
 * unique generalized abbreviations.
 * 
 * Generalized abbreviation of a word can be generated by replacing each
 * substring of the word by the count of characters in the substring. Take the
 * example of “ab” which has four substrings: “”, “a”, “b”, and “ab”. After
 * replacing these substrings in the actual word by the count of characters we
 * get all the generalized abbreviations: “ab”, “1b”, “a1”, and “2”.
 */
public class GeneralizedAbbreviation {
  public static List<String> generateGeneralizedAbbreviation(String word) {
    List<String> result = new ArrayList<>();

    return result;
  }
  public static void main(String[] args) {
    List<String> result = generateGeneralizedAbbreviation("BAT");
    System.out.println("Generalized abbreviation are: " + result);

    result = generateGeneralizedAbbreviation("code");
    System.out.println("Generalized abbreviation are: " + result);
  }

}
